#!/bin/bash

USAGE="Usage: $(basename "$0") <fs_subject_dir> <aparc> <ribbon>

Converts a .annot file into volumetric ROIs, which are stored in
fs_subject_dir/aparc_roi/, as well as a text file of all volumes.
Will do this bilaterally by default. Including an argument in the
third field will sample from the cortical ribbon.
Valid inputs for aparc are: aparc, aparc.a2009s, aparc.DKTatlas"

if [[ $# -eq 0 ]] ; then
    echo "$USAGE"
    exit 0
fi

SUBJECT="${1%/}"
ANNOT=$2

SUBJECT_BASE="$(basename "$1")"
SUBJECTS_DIR="$(dirname "$1")"
echo $SUBJECTS_DIR
OUT_DIR="$SUBJECT"/"$ANNOT"_roi

if [ ! -e "$OUT_DIR" ]; then
    mkdir "$OUT_DIR"
else 
    echo "$OUT_DIR" already exists, won\'t duplicate
    exit 1
fi

for hemi in lh rh; do
    mri_annotation2label \
        --subject "$SUBJECT_BASE" \
        --hemi "$hemi" \
        --outdir "$OUT_DIR" \
        --annotation "$ANNOT"
done

LABELS=$(ls "$OUT_DIR")
for label in $LABELS; do
    IFS=. read -ra name <<< "$label"
    hemi="${name[0]}"
    out_vol="$OUT_DIR"/"$hemi"."${name[1]}".nii.gz
    out_vol="$(realpath "$out_vol")"
    if [ -z "$3" ]; then
        echo "No 4th argument supplied, so sampling at white surf"
        mri_label2vol \
            --label "$OUT_DIR"/"$label" \
            --o "$out_vol" \
            --hemi "$hemi" \
            --fillthresh 0.5 \
            --subject "$SUBJECT_BASE" \
            --identity \
            --temp "$SUBJECT"/mri/orig.mgz
        echo "$out_vol" >> "$OUT_DIR"/roi_wmedge.txt
    else
        echo "$3 detected, sampling the cortical ribbon"
        mri_label2vol \
            --label "$OUT_DIR"/"$label" \
            --o "$out_vol" \
            --hemi "$hemi" \
            --fill-ribbon \
            --fillthresh 0.5 \
            --subject "$SUBJECT_BASE" \
            --identity \
            --temp "$SUBJECT"/mri/orig.mgz
        echo "$out_vol" >> "$OUT_DIR"/roi_ribbon.txt
    fi
    rm "$OUT_DIR"/"$label"
done
