#!/bin/bash

USAGE="Usage: $(basename "$0") <fs_subject_dir> <aparc>

Converts a .annot file into volumetric ROIs, which are stored in
fs_subject_dir/aparc_roi/, as well as a text file of all volumes.
Will do this bilaterally by default. Since I'm lazy, makes ROIs
sampling at the white surf and whole cortical ribbon.
Valid inputs for aparc are: aparc, aparc.a2009s, aparc.DKTatlas"

if [[ $# -eq 0 ]] ; then
    echo "$USAGE"
    exit 0
fi

SUBJECT="${1%/}"
ANNOT=$2

SUBJECT_BASE="$(basename "$1")"
SUBJECTS_DIR="$(dirname "$1")"
echo $SUBJECTS_DIR
OUT_DIR="$SUBJECT"/"$ANNOT"_roi

if [ -e "$OUT_DIR" ]; then
    rm -rf "$OUT_DIR"
else
    mkdir "$OUT_DIR"
fi

for hemi in lh rh; do
    mri_annotation2label \
        --subject "$SUBJECT_BASE" \
        --hemi "$hemi" \
        --outdir "$OUT_DIR" \
        --annotation "$ANNOT"
done

LABELS=$(ls "$OUT_DIR")
for label in $LABELS; do
    IFS=. read -ra name <<< "$label"
    hemi="${name[0]}"
    out_vol="$OUT_DIR"/"$hemi"."${name[1]}"_wmedge.nii.gz
    out_vol="$(realpath "$out_vol")"
    mri_label2vol \
        --label "$OUT_DIR"/"$label" \
        --o "$out_vol" \
        --hemi "$hemi" \
        --fillthresh 0.5 \
        --subject "$SUBJECT_BASE" \
        --identity \
        --temp "$SUBJECT"/mri/orig.mgz
    echo "$out_vol" >> "$OUT_DIR"/roi_wmedge.txt
    # out_vol="$OUT_DIR"/"$hemi"."${name[1]}"_ribbon.nii.gz
    # out_vol="$(realpath "$out_vol")"
    # mri_label2vol \
    #     --label "$OUT_DIR"/"$label" \
    #     --o "$out_vol" \
    #     --hemi "$hemi" \
    #     --fill-ribbon \
    #     --subject "$SUBJECT_BASE" \
    #     --identity \
    #     --temp "$SUBJECT"/mri/orig.mgz
    # echo "$out_vol" >> "$OUT_DIR"/roi_ribbon.txt
    rm "$OUT_DIR"/"$label"
done
