#!/bin/bash

USAGE="Usage: $(basename "$0") <fs_subject_dir>

Uses mri_binarize to extract cortical white matter, all white matter,
ventricles, all grey matter, and subcortical grey matter.
Stores them in fs_subject_dir/mri/"

if [[ $# -eq 0 ]] ; then
    echo "$USAGE"
    exit 0
fi

SUBJECT="${1%/}"

MRI_DIR="$SUBJECT"/mri
declare -a MASKS=("ctx-wm" "all-wm" "ventricles" "gm" "subcort-gm")

for mask_opt in "${MASKS[@]}"; do
  echo Creating binary "$mask_opt" mask...
  mri_binarize \
    --i "$MRI_DIR"/aparc+aseg.mgz \
    --"${mask_opt}" \
    --o "$MRI_DIR"/${mask_opt}.nii.gz
done
