#!/bin/bash

# INPUT: Freesurfer subject dir
# OUTPUT: Binary masks for grey matter, white matter, and ventricles in mri/

SUBJECT=$1

MRI_DIR="$SUBJECT"/mri
declare -a MASKS=("ctx-wm" "all-wm" "ventricles" "gm" "subcort-gm")

for mask_opt in "${MASKS[@]}"; do
  echo Creating binary "$mask_opt" mask...
  mri_binarize \
    --i "$MRI_DIR"/aparc+aseg.mgz \
    --"${mask_opt}" \
    --o "$MRI_DIR"/${mask_opt}.nii.gz
done
