#!/bin/bash

USAGE="
Usage: orig2raw  <FS_SUBJECT_DIR>

Takes a freesurfer subject directory as input, uses tkregister2 to register
orig.mgz (conformed space) to rawavg.mgz (native anat space) using headers,
and writes an FSL-style transformation to:
<FS_SUBJECT_DIR>/mri/transforms/fs2anat.mat"

# Uses tkregister2 to register orig to rawavg using header info 

if [ $# -eq 0 ] 
then 
  echo $USAGE
  exit 1
fi 

SUBJECT=$1

MRI_DIR="$SUBJECT"/mri
XFM_DIR="$MRI_DIR"/transforms

echo Registering orig to rawavg for "$SUBJECT"...
tkregister2 \
    --mov "$MRI_DIR"/orig.mgz \
    --targ "$MRI_DIR"/rawavg.mgz \
    --regheader \
    --fslregout "$XFM_DIR"/fs2anat.mat  \
    --identity \
    --noedit \
    --reg "$XFM_DIR"/register.dat

rm "$XFM_DIR"/register.dat
