#!/bin/bash

subj="${1%/}"
mri_dir=$subj/mri

mri_binarize \
  --i $mri_dir/aparc+aseg.mgz \
  --match 251 252 253 254 255 \
  --o $mri_dir/cc.nii.gz

for surf in pial white; do
  for hemi in lh rh; do
    mri_surf2vol \
      --mkmask \
      --hemi ${hemi} \
      --surf ${surf} \
      --identity $subj \
      --template $mri_dir/orig.mgz \
      --o $mri_dir/${hemi}_${surf}.nii.gz
  done
  fslmaths $mri_dir/lh_${surf}.nii.gz \
    -add $mri_dir/rh_${surf}.nii.gz \
    -bin \
    -sub $mri_dir/cc.nii.gz \
    -sub $mri_dir/ventricles.nii.gz \
    -thr 0 -bin \
    $mri_dir/${surf}_surf.nii.gz
  rm $mri_dir/lh_${surf}.nii.gz $mri_dir/rh_${surf}.nii.gz $mri_dir/cc.nii.gz
done
